travis:
  secure:
    BINSTAR_TOKEN: E25dhdx4HKGi7QdFBuUg/kAgOHH5Lb92MGRaufcRP3NYqevpsFDFS55theTCyLdsozwtcnapmPOYXu+yGAwZbdW3JggzJk1Nq8XJs9yInluR8FUIsBangzgxd+DdRke1WbPfLkBGobcxNeJESa9yJwjyM9KdyRazO2DE/sQLLaML2hIn7GrjGzgoU1AOR5TJKZLc6dkRNll5fKATEjXF207PeOVmRxgO1JPeME3YBtdhUIuO3V0JeCmnTMNyjhxInicCGbIUpGb7hy+iPxmbrD/eaKrPp2of4ij3GfZCUWSDDaNGwWG6Om0IdYOJ8CCMhOn0ut6j7JcW5mkWTz76bZ23aHZX7cHcZUOkLWS6XFuZmHEYgAX4d3BRAF86BfPedMxn76F1dnGOANKD4ZxNlwbRSTc8ulsvAfftRjXkawRvWxCiMEVOMI09hsfxNqfwnZcy5QSu6x/z/37hVm0SLk6ahPX/r/Gfx9aIZtaEoEzKPNgQ/d2aswitMYMKkAenMWZ8T1otQvLJLRze48B4Jp04ah0+8wp6PY8pNa5Ut2aD2aTtyaOjxNypxhPFsycniw35gDoP8C4wjmBoKuuDdfJzd84FFQb0USqbETn9w7oPBGQ4vnQgMhCrtsOiG6LFvLAZPZvJtva0bazQ8CWvrqfeH8RsfixonDVvDHEkafQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
